version: '3.6'

services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - '4040:4040'

  mainServer:
    image: python:3.9
    container_name: mainServer_local
    volumes:
      - ./requirements.txt:/code/requirements.txt
      - ./app:/code/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Server-Dockerfile

  DataBase:
    restart: always
    image: pgrouting/pgrouting:13-3.1-3.1.3
    container_name: routingDB_local
    volumes:
      - ./sql-scripts/result_2po_4pgr.sql:/docker-entrypoint-initdb.d/setup.sql
    env_file:
      - .env
    ports:
      - '5432:5432'